---
- name: Configure home server
  hosts: home_server
  become: yes
  roles:
    # - { role: common, tags: ['common'] }
    # - { role: docker, tags: ['docker'] }
    # - { role: artis3n.tailscale, tags: ['tailscale'] }
    - role: artis3n.tailscale
      vars:
        # Example pulling the API key from the env vars on the host running Ansible
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"
