---
- name: Configure home server
  hosts: home_server
  become: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }
    - { role: neovim, tags: ['neovim'] }
