- name: Configure Tailscale on servers
  hosts: home_server
  become: yes
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"
- name: Configure Tailscale to not override local DNS
  ansible.builtin.command:
    cmd: tailscale up --accept-dns=false
  register: tailscale_up
  changed_when: "'already' not in tailscale_up.stderr"
