---
- name: Update apt package list
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    
- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - software-properties-common
      - apt-transport-https
      - gnupg
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install Python Docker package
  apt:
    name: python3-docker
    state: present
