services:

  web:
    image: nginx:latest
    container_name: proxy
    depends_on:
      - homepage
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./quoggioserver.tailf385d.ts.net.crt:/etc/nginx/certs/cert.crt:ro
      - ./quoggioserver.tailf385d.ts.net.key:/etc/nginx/certs/cert.key:ro
    networks:
      - proxy-network

  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
    networks:
      - proxy-network
    restart: unless-stopped

  actualtap-py:
    container_name: actualtap-py
    image: ghcr.io/bobokun/actualtap-py:latest
    ports:
      - 8000:8000
    volumes:
      - ./actualtap_config:/config
    networks:
      - proxy-network

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage_files/config:/app/config
      - ./homepage_files/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    networks:
      - proxy-network
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin_files/config:/config
      - ./jellyfin_files/cache:/cache
      - type: bind
        source: /media
        target: /media
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
