---
- name: Configure Bazarr service
  set_fact:
    bazarr_service:
      name: bazarr
      image: lscr.io/linuxserver/bazarr:1.5.6
      container_name: bazarr
      ports:
        - "6767:6767"
      volumes:
        - ./bazarr/config:/config
        - "{{ media_dir }}/Shows:/tv"
        - "{{ media_dir }}/Movies:/movies"
      environment:
        - "PUID={{ puid }}"
        - "PGID={{ pgid }}"
        - "TZ={{ tz }}"
      networks:
        - qnet
      restart: unless-stopped

- name: Setup Bazarr directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/bazarr/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
