---
- name: Configure homepage service
  set_fact:
    homepage_service:
      name: homepage
      image: ghcr.io/gethomepage/homepage:latest
      container_name: homepage
      ports:
        - "3000:3000"
      volumes:
        - ./homepage/config:/app/config
        - ./homepage/images:/app/public/images
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - proxy-network
      restart: unless-stopped

- name: Setup Homepage directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/homepage_files/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "images"
    - "config"

- name: Copy homepage configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_dir }}/homepage/config"
  become: true
  with_fileglob:
    - "files/homepage_config/*"

- name: Copy homepage images
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_dir }}/homepage/images"
  become: true
  with_fileglob:
    - "files/images/*"
