---
- name: Setup Homepage directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/homepage_files/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "images"
    - "config"

- name: Copy homepage configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_dir }}/homepage_files/config"
  become: true
  with_fileglob:
    - "files/homepage_config/*"

- name: Copy homepage images
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_dir }}/homepage_files/images"
  become: true
  with_fileglob:
    - "files/images/*"
