---
- name: Configure jellyfin service
  set_fact:
    jellyfin_service:
      name: jellyfin
      image: jellyfin/jellyfin
      container_name: jellyfin
      ports:
        - 8096:8096
      volumes:
        - ./jellyfin/config:/config
        - ./jellyfin/cache:/cache
        - type: bind
          source: /media
          target: /media
      networks:
        - proxy-network
      restart: unless-stopped

- name: Setup Jellyfin directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/jellyfin/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "config"
    - "cache"
