---
- name: Configure qBittorrent service
  set_fact:
    qbittorrent_service:
      name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:5.2.2
      container_name: qbittorrent
      ports:
        - 8585:8585
        - 6881:6881
        - 6881:6881/udp
      volumes:
        - ./qbittorrent/config:/config
        - "{{ media_dir }}/downloads:/downloads"
      networks:
        - qnet
      restart: unless-stopped
      environment:
        - "PUID={{ puid }}"
        - "PGID={{ pgid }}"
        - "TZ={{ tz }}"
        - WEBUI_PORT=8585

- name: Setup qBittorrent directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/qbittorrent/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "config"
