---
- name: Configure qBittorrent service
  set_fact:
    qbittorrent_service:
      name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      ports:
        - 8585:8585
        - 6881:6881
        - 6881:6881/udp
      volumes:
        - ./qbittorrent/config:/config
        - /media/downloads:/downloads
      networks:
        - proxy-network
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Rome
        - WEBUI_PORT=8585

- name: Setup qBittorrent directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/qbittorrent/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "config"

