- name: Configure Radarr service
  set_fact:
    radarr_service:
      name: radarr
      image: lscr.io/linuxserver/radarr:6.2.1
      container_name: radarr
      ports:
        - "7878:7878"
      volumes:
        - ./radarr/config:/config
        - "{{ media_dir }}/Movies:/movies"
        - "{{ media_dir }}/downloads:/downloads"
      environment:
        - "PUID={{ puid }}"
        - "PGID={{ pgid }}"
        - "TZ={{ tz }}"
      networks:
        - qnet
      restart: unless-stopped

- name: Setup Radarr directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/radarr/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
