---
- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Create Nginx proxy manager volume folders
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}/npmdata"
    - "{{ docker_compose_dir }}/letsencrypt"

- name: Combine services
  set_fact:
    services: "{{ [homepage_service, jellyfin_service, actual_service, audiobookshelf_service, vikunja_service] }}"

- name: Render Docker Compose file
  template:
    src: compose.yml.j2
    dest: "{{ docker_compose_dir }}/compose.yml"
