---
- name: Configure Sonarr service
  set_fact:
    sonarr_service:
      name: sonarr
      image: lscr.io/linuxserver/sonarr:latest
      container_name: sonarr
      ports:
        - 8989:8989
      volumes:
        - ./sonarr/config:/config
        - /media/Shows:/tv
        - /media/downloads:/downloads
      networks:
        - proxy-network
      restart: unless-stopped
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Rome

- name: Setup Sonarr directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/sonarr/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "config"
